title: ""

plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

permalink: pretty
enable_copy_code_button: true
search_enabled: false
heading_anchors: true
color_scheme: dark

nav_enabled: false

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false

back_to_top: false
footer_content: ""
last_edit_timestamp: false
gh_edit_link: false

liquid:
  error_mode: strict
  strict_filters: true
include: [".well-known"]
